on: [push, pull_request]

env:
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}

jobs:
  Linux:
    runs-on: ubuntu-18.04
    env:
      CONAN_CLANG_VERSIONS: 8
      CONAN_DOCKER_IMAGE: conanio/clang8
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Conan
        run: |
          pip install bincrafters_package_tools
          conan user
      - name: Run
        run: |
          bincrafters-package-tools --auto

  Windows:
    runs-on: windows-latest
    env:
      CONAN_VISUAL_VERSIONS: "16"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Conan
        run: |
          pip install bincrafters_package_tools
          conan user
      - name: Run
        run: |
          bincrafters-package-tools --auto
